# Generated by Django 5.0.1 on 2024-02-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Socios',
            fields=[
                ('DNI', models.CharField(unique=True)),
                ('numero_socio', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField()),
            ],
        ),
    ]
