# Generated by Django 5.0.1 on 2024-02-15 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sociosrcd', '0002_alter_socios_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socios',
            name='DNI',
            field=models.CharField(unique=True),
        ),
    ]
