# Generated by Django 5.0.1 on 2024-02-15 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sociosrcd', '0003_alter_socios_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socios',
            name='DNI',
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
